### ISSUE TITLE
[NEW MOD] THE POULLUTION MOD

### ISSUE THREAD

**Issue by bluejet5** [hackclub/modpack#10]
### Mod Name

ill just send you the link

### Mod Link

PLEASE MAN I BEG YOU THIS MAY BE VERY BAD AND OP AND MAY CRASH THE SERVER BUT I NEED IT PLEASE https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys/files https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms/files
AND I CHECKED ALL OF THE CONFIRMATION

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by alx-alexpark** [comment]
I'm fine with this mod being installed, but some may find it annoying. Waiting for @the456gamer to decide.

**Comment by 456dev** [comment]
Personally, I'm leaning to no.
I've had a look, can you send me a like to the source, like the template says?

**Comment by bluejet5** [comment]
![sad light skin stare](https://github.com/hackclub/modpack/assets/133557259/a8966105-1827-476a-9660-fc2679f712a9)

this is how i feel about it being rejected
