### ISSUE TITLE
[NEW MOD] Valkyrien Skies

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [hackclub/modpack#11]
### Mod Name

Valkyrien Skies 

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by alx-alexpark** [comment]
Cool mod some other people have also been asking for, I approve. Waiting for @the456gamer confirmation.

**Comment by 456dev** [comment]
This mod set looks cool, I approve.
Related #12 #13
