### ISSUE TITLE
[NEW MOD] Eureka! Airships!

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [hackclub/modpack#12]
### Mod Name

Eureka! Airships! (Forge/Fabric)

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/eureka-ships

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by alx-alexpark** [comment]
Looks like a pretty essential add-on to the previous mod you suggested. Awaiting @the456gamer's response.
