### ISSUE TITLE
dash mod

### ISSUE THREAD

**Issue by saucesaurus** [hackclub/modpack#14]
### Mod Name

Double-Tap Dash

### Mod Link

https://modrinth.com/mod/double-tap-dash

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by alx-alexpark** [comment]
In my opinion, this mod is not very needed because our server is not based around PVP neither around significant PVE.

**Comment by 456dev** [comment]
I'd be inclined to agree, and furthermore I cannot see a 1.18.2 forge version

**Comment by 456dev** [comment]
This seems like a workable alternative, possible in-game atm
https://botaniamod.net/lexicon.html#baubles/dodge_ring
