### ISSUE TITLE
dinosaurs

### ISSUE THREAD

**Issue by 123456789020** [hackclub/modpack#17]
### Mod Name

alternacraft

### Mod Link

https://www.curseforge.com/minecraft/mc-mods/alternacraft/files/4359573

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by alx-alexpark** [comment]
No, I don't think this mod fits our modpack.

**Comment by 456dev** [comment]
doesnt fit, and the world has already been generated
