### ISSUE TITLE
sus mod

### ISSUE THREAD

**Issue by bluejet5** [hackclub/modpack#9]
### Mod Name

the frankster prankster mod https://www.youtube.com/watch?v=sUTy1HziQMQ&t=4s

### Mod Link

![the light skin stare](https://github.com/hackclub/modpack/assets/133557259/bc8375b3-907e-4202-aa08-67a998813062)

### Confirmation

- [X] The mod is available for **Forge 1.18.2**
- [X] The mod is open source
- [X] There are no incompatabilities or conflicts with currently installed mods

**Comment by bluejet5** [comment]
i hope you like my respo
![the light skin stare](https://github.com/hackclub/modpack/assets/133557259/d46627a1-15d4-464f-8486-5e7eb61f6c0b)
nse

**Comment by 456dev** [comment]
No mod in issue
